<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * CVE-13: Malware Risk / Malicious Restoration.
     * Adding a cryptographic signature to backups to ensure they were
     * generated by THIS system and have not been tampered with in storage.
     */
    public function up(): void
    {
        Schema::table('tenant_backups', function (Blueprint $table) {
            $table->string('signature', 128)->nullable()->after('checksum')
                ->comment('HMAC signature of the checksum, signed by APP_KEY.');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('tenant_backups', function (Blueprint $table) {
            $table->dropColumn('signature');
        });
    }
};
