/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Light palette — sage as sole accent, everything else neutral.
        bg:           '#FAFAF7',
        surface:      '#FFFFFF',
        surface2:     '#F4F3EE',
        ink:          '#15201C',
        ink2:         '#3F4945',
        muted:        '#83898A',
        faint:        '#C1C5C2',
        divider:      'rgba(21,32,28,0.06)',
        hairline:     'rgba(21,32,28,0.04)',
        accent:       '#2F8F6F',
        'accent-ink': '#FFFFFF',
        'accent-soft':'#E9F2EC',
        tint:         '#F2F0EA',
        ok:           '#2F8F6F',
        warn:         '#9A7234',
        danger:       '#B4584C',
        'bubble-in':  '#F4F3EE',
        'bubble-out': '#E5EFE9',
        // Dark equivalents
        'd-bg':           '#0F1614',
        'd-surface':      '#171F1C',
        'd-surface2':     '#1C2421',
        'd-ink':          '#EEF1EE',
        'd-ink2':         '#C4CAC7',
        'd-muted':        '#828B87',
        'd-faint':        '#525A57',
        'd-divider':      'rgba(255,255,255,0.05)',
        'd-hairline':     'rgba(255,255,255,0.03)',
        'd-accent':       '#6CBFA0',
        'd-accent-ink':   '#0F1614',
        'd-accent-soft':  '#1B2A24',
        'd-tint':         '#1C2421',
        'd-bubble-in':    '#1C2421',
        'd-bubble-out':   '#243A33',
        'd-ok':           '#6CBFA0',
        'd-warn':         '#C9A672',
        'd-danger':       '#D58F84',
      },
      fontFamily: {
        sans: ['System'],
        mono: ['Menlo', 'Courier'],
      },
      borderRadius: {
        xl: '22px',
        lg: '14px',
        md: '10px',
        sm: '6px',
      },
    },
  },
  plugins: [],
};
