<?php

namespace App\Http\Controllers\Backup;

use App\Http\Controllers\Controller;
use App\Models\ActivityLog;
use App\Models\TenantBackup;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

/**
 * SecureDownloadController
 * ════════════════════════════════════════════════════════
 * Handles the actual file streaming for backup downloads.
 *
 * This controller is reached via a TEMPORARY SIGNED ROUTE that was
 * generated by BackupController::download(). It is not directly
 * accessible by typing in a URL — the signed token would be invalid.
 *
 * Security model:
 *  - Laravel's `signed` middleware validates the route signature & expiry.
 *  - Team ID in the signed URL is re-checked against the backup record.
 *  - The user MUST still be authenticated (auth:sanctum middleware).
 *  - The file is streamed from local (private) storage, never from public/.
 *  - A second audit log entry is written for the actual file download.
 *
 * File path is built from the database record — never from user input.
 * This eliminates path traversal vulnerabilities entirely.
 * ────────────────────────────────────────────────────────
 */
class SecureDownloadController extends Controller
{
    /**
     * Stream the backup file to the authenticated, authorized user.
     *
     * Route: GET /backups/{id}/download/stream
     * Middleware: auth:sanctum, signed (validates temporarySignedRoute token)
     *
     * @param  string  $id  The TenantBackup UUID or ID
     * @return \Symfony\Component\HttpFoundation\StreamedResponse|\Illuminate\Http\RedirectResponse
     */
    public function stream(Request $request, $id)
    {
        // The `signed` middleware on the route has already validated:
        //   - The URL signature is authentic (not forged)
        //   - The URL has not expired (5-minute TTL)
        //
        // We still need to re-verify the team context to prevent
        // a valid token being used by a different tenant's session.

        $teamIdFromToken = (int) $request->query('team');

        // 1. Load backup and re-validate team ownership
        $backup = TenantBackup::where('id', $id)
            ->where('team_id', $teamIdFromToken)
            ->where('status', 'completed')
            ->firstOrFail();

        // 2. Re-verify the session user belongs to the team in the token
        $user = auth()->user();
        $currentTeamId = $user->currentTeam?->id;

        if ($currentTeamId !== $backup->team_id && ! $user->is_super_admin) {
            $this->auditLog(
                $backup->team_id,
                'backup.download_rejected',
                "Signed download rejected: session team mismatch for backup {$backup->filename}",
                [
                    'backup_id' => $backup->id,
                    'token_team_id' => $teamIdFromToken,
                    'session_team_id' => $currentTeamId,
                ]
            );

            abort(403, 'Session team does not match the backup owner.');
        }

        // 3. Build storage path from DB record — NEVER from user-supplied input
        $storagePath = "backups/{$backup->path}{$backup->filename}";

        if (! Storage::disk('local')->exists($storagePath)) {
            abort(404, 'Backup file no longer exists on server.');
        }

        // 4. Audit log the actual download (separate from URL issuance)
        $this->auditLog($backup->team_id, 'backup.downloaded', "Backup file downloaded: {$backup->filename}", [
            'backup_id' => $backup->id,
            'filename' => $backup->filename,
            'size' => $backup->size,
        ]);

        // 5. Stream from private local storage with a safe, sanitised filename
        $safeFilename = preg_replace('/[^a-zA-Z0-9_\-\.]/', '_', $backup->filename);

        return response()->streamDownload(function () use ($storagePath) {
            // Stream in 1MB chunks to keep memory usage bounded for large backups
            $stream = Storage::disk('local')->readStream($storagePath);
            while (! feof($stream)) {
                echo fread($stream, 1024 * 1024);
                flush();
            }
            fclose($stream);
        }, $safeFilename, [
            'Content-Type' => 'application/octet-stream',
            'Content-Disposition' => "attachment; filename=\"{$safeFilename}\"",
            'Content-Length' => $backup->size,
            'Cache-Control' => 'no-store, no-cache, must-revalidate',
            'Pragma' => 'no-cache',
            'X-Content-Type-Options' => 'nosniff',
        ]);
    }

    // ─────────────────────────────────────────────────────────────────────
    // Internal Helpers
    // ─────────────────────────────────────────────────────────────────────

    private function auditLog(int $teamId, string $action, string $description, array $properties = []): void
    {
        try {
            ActivityLog::create([
                'team_id' => $teamId,
                'user_id' => auth()->id(),
                'action' => $action,
                'description' => $description,
                'ip_address' => request()->ip(),
                'properties' => array_merge($properties, [
                    'user_agent' => request()->userAgent(),
                ]),
            ]);
        } catch (Exception $e) {
            \Log::error('Backup download audit log failed: '.$e->getMessage());
        }
    }
}
